### ISSUE TITLE
Build crashes if the system TZ is not set

### ISSUE THREAD

**Issue by Dalgona** [Dalgona/Serum#13]
**Crash site:**

```
 ~/repo/Serum (master)
 -> ./serum server ~/repo/serum-site -p 5757
Serum -- Yet another simple static website generator
Version 0.9.0. Copyright (C) 2016 Dalgona. <dalgona@hontou.moe>

Reading project metadata `/home/dalgona/repo/serum-site/serum.json`...
Rebuilding Website...
Created directory `/tmp/serum_-AAAACQvUCg/`.
Reading project metadata `/home/dalgona/repo/serum-site/serum.json`...
Loading templates...
Scanning `/home/dalgona/repo/serum-site/pages/` directory...
Compiling main navigation HTML stub...
⚡️  Starting parallel build...
** (EXIT from #PID<0.66.0>) shutdown: failed to start child: Serum.DevServer.Service
    ** (EXIT) an exception was raised:
        ** (RuntimeError) Unable to locate the current timezone!
            lib/timezone/timezone_local.ex:230: Timex.Timezone.Local.read_timezone_data/3
            lib/timezone/timezone_local.ex:109: Timex.Timezone.Local.localtz/2
            lib/timezone/timezone_local.ex:58: Timex.Timezone.Local.lookup/1
            lib/timezone/timezone.ex:52: Timex.Timezone.local/1
            lib/timezone/timezone.ex:73: Timex.Timezone.name_of/1
            lib/datetime/helpers.ex:33: Timex.DateTime.Helpers.construct/2
            (serum) lib/serum/build/post_builder.ex:139: Serum.Build.PostBuilder.extract_date/1
            (serum) lib/serum/build/post_builder.ex:66: Serum.Build.PostBuilder.post_task/3

09:43:32.292 [error] Task #PID<0.1018.0> started from #PID<0.70.0> terminating
** (RuntimeError) Unable to locate the current timezone!
    lib/timezone/timezone_local.ex:230: Timex.Timezone.Local.read_timezone_data/3
    lib/timezone/timezone_local.ex:109: Timex.Timezone.Local.localtz/2
    lib/timezone/timezone_local.ex:58: Timex.Timezone.Local.lookup/1
    lib/timezone/timezone.ex:52: Timex.Timezone.local/1
    lib/timezone/timezone.ex:73: Timex.Timezone.name_of/1
    lib/datetime/helpers.ex:33: Timex.DateTime.Helpers.construct/2
    (serum) lib/serum/build/post_builder.ex:139: Serum.Build.PostBuilder.extract_date/1
    (serum) lib/serum/build/post_builder.ex:66: Serum.Build.PostBuilder.post_task/3
Function: &Serum.Build.PostBuilder.post_task/3
    Args: ["/home/dalgona/repo/serum-site/posts/", "/tmp/serum_-AAAACQvUCg/posts/", "2016-11-26-1934-welcome-to-serum"]
```

* Reason: Timex complains that the system timezone is not set.
* Possible workarounds:
    * Fallback to UTC
    * Use naive datetime
    * *more?*

**Comment by Dalgona** [comment]
3a79673 enforces the system timezone to be set.

The build process will be aborted if the tz is not set.
