### ISSUE TITLE
Some test cases cannot not run asynchronously.

### ISSUE THREAD

**Issue by Dalgona** [Dalgona/Serum#38]
It seems that test cases which use functions from `ExUnit.CaptureIO` module cannot run at the same time.

```
1) test fallback string format bad date format (Serum.ProjecTest)
    test/serum/project_test.exs:31
    ** (RuntimeError) IO device registered at :standard_error is already captured
    code: warn = capture_io(:stderr, fn -> send(self(), Project.new(map)) end)
    stacktrace:
      (ex_unit) lib/ex_unit/capture_io.ex:144: ExUnit.CaptureIO.do_capture_io/3
      test/serum/project_test.exs:35: (test)
2) test fallback string format good (Serum.ProjecTest)
    test/serum/project_test.exs:14
    ** (RuntimeError) IO device registered at :standard_error is already captured
    code: warn = capture_io(:stderr, fn -> send(self(), Project.new(map)) end)
    stacktrace:
      (ex_unit) lib/ex_unit/capture_io.ex:144: ExUnit.CaptureIO.do_capture_io/3
      test/serum/project_test.exs:18: (test)
3) test fallback string format both the date format and the list title format are bad (Serum.ProjecTest)
    test/serum/project_test.exs:65
    ** (RuntimeError) IO device registered at :standard_error is already captured
    code: warn = capture_io(:stderr, fn -> send(self(), Project.new(map)) end)
    stacktrace:
      (ex_unit) lib/ex_unit/capture_io.ex:144: ExUnit.CaptureIO.do_capture_io/3
      test/serum/project_test.exs:69: (test)
```

**Comment by Dalgona** [comment]
[From the doc for `ExUnit.CaptureIO.capture_io/1`:](https://hexdocs.pm/ex_unit/ExUnit.CaptureIO.html#capture_io/1)

> Note that when capturing something other than `:stdio`, the test should run with `async: false`.

Why did I miss this sentence... anyway I learned a new thing.
