### ISSUE TITLE
Error when building serum

### ISSUE THREAD

**Issue by chrisallenmoore** [Dalgona/Serum#4]
Got this error when building a post with serum. 

```
$ serum build ./
Serum -- Yet another simple static website generator
Version 0.9.0. Copyright (C) 2016 Dalgona. <dalgona@hontou.moe>


Rebuilding Website...
Reading project metadata `./serum.json`...
Loading templates...
Created directory `./site/`.
Compiling main navigation HTML stub...
⌛️  Starting sequential build...
  GEN  ./pages/index.md -> ./site/index.html
  GEN  ./pages/about/index.html -> ./site/about/index.html
** (Timex.Format.FormatError) got {:format, "Expected at least one parser to succeed at line 1, column 0."} while retrieving Exception.message/1 for %Timex.
Format.FormatError{message: {:format, "Expected at least one parser to succeed at line 1, column 0."}} (expected a string)
    lib/format/datetime/formatter.ex:53: Timex.Format.DateTime.Formatter.lformat!/4
    (serum) lib/serum/build/post_builder.ex:112: Serum.Build.PostBuilder.extract_date/1
    (serum) lib/serum/build/post_builder.ex:44: Serum.Build.PostBuilder.post_task/3
    (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:651: Enum.each/2
    (serum) lib/serum/build/post_builder.ex:33: Serum.Build.PostBuilder.launch_post/4
    (serum) lib/serum/build/post_builder.ex:15: Serum.Build.PostBuilder.run/3
    (serum) lib/serum/build.ex:91: Serum.Build.launch_tasks/3
```

The post file name
```
2016-10-01-1946-my-latest-post.md
```

The post contents
```
# Hello! This is My Latest Post
# sample, hello

Lorem ipsum dolor sit amet, consectetur adipiscing ...

```

**Comment by Dalgona** [comment]
Thank you for your report. I'll figure out what's making problems as soon as I get back home. 👍

**Comment by Dalgona** [comment]
I figured it out. There was a typo issue in [`lib/serum/init.ex:51`](https://github.com/Dalgona/Serum/blob/master/lib/serum/init.ex#L51), which produced `serum.json` with invalid default date format string.

**Comment by Dalgona** [comment]
@chrisallenmoore Please test with the latest commit on `fix/issue-4` branch. I hope this fixes this problem.

**Comment by chrisallenmoore** [comment]
tested and your fix works! Thanks so much!

**Comment by chrisallenmoore** [comment]
leaving this open for you to close ;)

**Comment by Dalgona** [comment]
Merged to `master` and `dev/autobuild`. Thanks again!
